# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MaybeDont < Formula
  desc "Guardrails for agentic AI"
  homepage "https://maybedont.ai"
  version "1.6.1"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybedont/releases/releases/download/v1.6.1/maybe-dont_1.6.1_darwin_x86_64.tar.gz"
      sha256 "450cb6360b80893f298dce35d39670f17ffd646413b57cbd3a4525b523ac539a"

      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybedont/releases/releases/download/v1.6.1/maybe-dont_1.6.1_darwin_arm64.tar.gz"
      sha256 "80e91cd78f6a748209e67c323e43c72722fe3991e8be578122881c548d9e326d"

      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.6.1/maybe-dont_1.6.1_linux_x86_64.tar.gz"
      sha256 "e7b9547d55a83a6fb3c6bddc1be831742a2c85b7abab20c2abbfea005a7a52e5"
      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.6.1/maybe-dont_1.6.1_linux_arm64.tar.gz"
      sha256 "7b58a88d6bcb7112fe73b62bf548bdc878653ab5c065a4b23a25e241b1fc3961"
      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
  end

  test do
    system "#{bin}/maybe-dont", "version"
  end
end
