# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MaybeDont < Formula
  desc "Guardrails for agentic AI"
  homepage "https://maybedont.ai"
  version "1.2.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybedont/releases/releases/download/v1.2.0/maybe-dont_1.2.0_darwin_x86_64.tar.gz"
      sha256 "5cf0267f3875d6ca25f477fda275af83251415dd6458ff1cfb48e6de9ed4b483"

      def install
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybedont/releases/releases/download/v1.2.0/maybe-dont_1.2.0_darwin_arm64.tar.gz"
      sha256 "196649102cff052379bcb34aadc9f65fbb7e7eab3c588f695d4b5461a5bfc053"

      def install
        bin.install "maybe-dont"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.2.0/maybe-dont_1.2.0_linux_x86_64.tar.gz"
      sha256 "1b7547c7604c2155899baa30b828b0cabbc10bcf435cf2de4b65538e0ca6e1e2"
      def install
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.2.0/maybe-dont_1.2.0_linux_arm64.tar.gz"
      sha256 "09465aae5137944cf4c3c778159da2769296503a7a86f78be37f0e11eac5bbc4"
      def install
        bin.install "maybe-dont"
      end
    end
  end

  test do
    system "#{bin}/maybe-dont", "version"
  end
end
