# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MaybeDont < Formula
  desc "Guardrails for agentic AI"
  homepage "https://maybedont.ai"
  version "1.5.0"
  license "Proprietary"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/maybedont/releases/releases/download/v1.5.0/maybe-dont_1.5.0_darwin_x86_64.tar.gz"
      sha256 "5c42d53e94eac10c5aaabe822bdc48aac6915a2105a3b1098699377638a00c6c"

      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/maybedont/releases/releases/download/v1.5.0/maybe-dont_1.5.0_darwin_arm64.tar.gz"
      sha256 "228d6e419ef1edb5f88d3a869488aeddb1d0d75cc9c1acdaa86d16950ea2e381"

      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.5.0/maybe-dont_1.5.0_linux_x86_64.tar.gz"
      sha256 "fd1eb8143db604c43b04b075cf9555f5296a4fedc94e737bce33ccfd456547e9"
      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/maybedont/releases/releases/download/v1.5.0/maybe-dont_1.5.0_linux_arm64.tar.gz"
      sha256 "291830d078032e3f3f15be459b603bb5140859ebedd98eaa703561cea9eeb9b5"
      define_method(:install) do
        bin.install "maybe-dont"
      end
    end
  end

  test do
    system "#{bin}/maybe-dont", "version"
  end
end
